mybatis:
  mapper-locations: xml/**/*.xml

spring:
   application:
     name: GreenGramVer1

   datasource:
     url: jdbc:mariadb://localhost/greengram_ver1
     username: root
     password: green502

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    default-model-expand-depth: 2
    default-models-expand-depth: -1
    display-request-duration: true
    operations-sorter: method
    path: /swagger